export const shows = [
    { 
        id: "1", 
        date: '2021-02-05',
        time: '6:20', 
        title: 'Amazing show', 
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.', 
        image: '', 
        thumb: 'circus1_small.jpg', 
        rating: 5, 
        gold: 895,
        silver: 795,
        bronze: 595, 
        category: 1, 
        artist: '',
        available: 10
    },
    { 
        id: "2", 
        date: '2021-02-06', 
        time: '6:20',
        title: 'Fantastic show', 
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.', 
        image: '', 
        thumb: 'circus2_small.jpg', 
        rating: 5, 
        gold: 895,
        silver: 795,
        bronze: 595, 
        category: 2, 
        artist: "",
        available: 2
    },
    { 
        id: "3", 
        date: '2021-02-12', 
        title: 'Magic Evening', 
        time: '6:20',
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.', 
        image: '', 
        thumb: 'circus1_small.jpg', 
        rating: 5, 
        gold: 895,
        silver: 795,
        bronze: 595, 
        category: 1, 
        artist: "",
        available: 0
    },
    { 
        id: "4", 
        date: '2021-02-13', 
        time: '6:20',
        title: '', 
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.', 
        image: '', 
        thumb: 'circus2_small.jpg', 
        rating: 5, 
        gold: 895,
        silver: 795,
        bronze: 595, 
        category: 3, 
        artist: "" 
    },
    { 
        id: "5", 
        date: '2021-02-19', 
        time: '6:20',
        title: 'Show name', 
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.', 
        image: '', 
        thumb: 'circus1_small.jpg', 
        rating: 5, 
        gold: 895,
        silver: 795,
        bronze: 595,
        category: 3,
        artist: "" 
    },
    { 
        id: "6", 
        date: '2021-02-20', 
        time: '6:20',
        title: 'Show name', 
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.', 
        image: '', 
        thumb: 'circus2_small.jpg', 
        rating: 5, 
        gold: 895,
        silver: 795,
        bronze: 595, 
        category: 3, 
        artist: "" 
    },
    { 
        id: "7", 
        date: '2021-03-05', 
        time: '6:20',
        title: 'Shown name', 
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.', 
        image: '', 
        thumb: 'circus1_small.jpg', 
        rating: 5, 
        gold: 895,
        silver: 795,
        bronze: 595, 
        category: 4, 
        artist: "" 
    },
    { 
        id: "8", 
        date: '2021-03-06', 
        time: '6:20',
        title: 'Show name', 
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.', 
        image: '', 
        thumb: 'circus2_small.jpg', 
        rating: 5, 
        gold: 895,
        silver: 795,
        bronze: 595, 
        category: 4, 
        artist: "" 
    },
    {
        id: "9",
        date: '2021-03-12',
        time: '6:20',
        title: 'Show name',
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.',
        image: '',
        thumb: 'circus2_small.jpg',
        rating: 5,
        gold: 895,
        silver: 795,
        bronze: 595,
        category: 4,
        artist: ""
    },
    {
        id: "10",
        date: '2021-03-20',
        time: '6:20',
        title: 'Show name',
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.',
        image: '',
        thumb: 'circus2_small.jpg',
        rating: 5,
        gold: 895,
        silver: 795,
        bronze: 595,
        category: 4,
        artist: ""
    },
    {
        id: "11",
        date: '2021-03-26',
        time: '6:20',
        title: 'Show name',
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.',
        image: '',
        thumb: 'circus2_small.jpg',
        rating: 5,
        gold: 895,
        silver: 795,
        bronze: 595,
        category: 4,
        artist: ""
    },
    {
        id: "12",
        date: '2021-06-05',
        time: '6:20',
        title: 'Show name',
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.',
        image: '',
        thumb: 'circus2_small.jpg',
        rating: 5,
        gold: 895,
        silver: 795,
        bronze: 595,
        category: 4,
        artist: ""
    },

    {
        id: "13",
        date: '2021-06-04',
        time: '6:20',
        title: 'Show name',
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.',
        image: '',
        thumb: 'circus2_small.jpg',
        rating: 5,
        gold: 895,
        silver: 795,
        bronze: 595,
        category: 4,
        artist: ""
    },
    {
        id: "14",
        date: '2022-01-11',
        time: '6:20',
        title: 'Show name',
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.',
        image: '',
        thumb: 'circus2_small.jpg',
        rating: 5,
        gold: 895,
        silver: 795,
        bronze: 595,
        category: 4,
        artist: ""
    },
    {
        id: "15",
        date: '2023-01-17',
        time: '6:20',
        title: 'Show name',
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum ipsum beatae autem ut amet possimus neque commodi suscipit, nostrum temporibus vitae. Libero facilis fuga, temporibus nulla odit accusantium porro repudiandae.',
        image: '',
        thumb: 'circus2_small.jpg',
        rating: 5,
        gold: 895,
        silver: 795,
        bronze: 595,
        category: 4,
        artist: ""
    }
    

];
export const categories = [
    { id: 1, name: 'Clown', icon: '<img src="img/circus1_small.jpg"/>', slug:'clown' },
    { id: 2, name: 'Acrobate', icon: '<img src="img/circus1_small.jpg"/>', slug:'acrobate' },
    { id: 3, name: 'Rope artist', icon: '<img src="img/circus1_small.jpg"/>', slug:"rope-artist"},
    { id: 4, name: 'Magician', icon: '<img src="img/circus1_small.jpg"/>', slug: 'magician' }

]